// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ==================== ANDROID ====================
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0v5YZg8G8FXrNUunRauLPpLLOE9MjPc0',
    appId: '1:994450931333:android:1d4d6eaab3a015a41ef3ec',
    messagingSenderId: '994450931333',
    projectId: 'ecommerce-39840',
    storageBucket: 'ecommerce-39840.firebasestorage.app',
  );

  // ==================== WEB ====================
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_WEB_API_KEY',             // Replace with your Web API key
    authDomain: 'YOUR_PROJECT.firebaseapp.com', // Replace with your Web authDomain
    projectId: 'ecommerce-39840',
    storageBucket: 'ecommerce-39840.appspot.com',
    messagingSenderId: '994450931333',
    appId: 'YOUR_WEB_APP_ID',               // Replace with your Web app ID
    measurementId: 'YOUR_MEASUREMENT_ID',  // Optional
  );

  // ==================== IOS ====================
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: 'YOUR_IOS_APP_ID',
    messagingSenderId: '994450931333',
    projectId: 'ecommerce-39840',
    storageBucket: 'ecommerce-39840.appspot.com',
    iosBundleId: 'YOUR_IOS_BUNDLE_ID',
    iosClientId: 'YOUR_IOS_CLIENT_ID',  // optional
    androidClientId: 'YOUR_ANDROID_CLIENT_ID', // optional
    measurementId: 'YOUR_MEASUREMENT_ID', // optional
  );

  // ==================== MACOS ====================
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: 'YOUR_MACOS_APP_ID',
    messagingSenderId: '994450931333',
    projectId: 'ecommerce-39840',
    storageBucket: 'ecommerce-39840.appspot.com',
    iosBundleId: 'YOUR_MACOS_BUNDLE_ID',
    iosClientId: 'YOUR_MACOS_CLIENT_ID', // optional
    measurementId: 'YOUR_MEASUREMENT_ID', // optional
  );

  // ==================== WINDOWS ====================
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'YOUR_WINDOWS_API_KEY',
    appId: 'YOUR_WINDOWS_APP_ID',
    messagingSenderId: '994450931333',
    projectId: 'ecommerce-39840',
    storageBucket: 'ecommerce-39840.appspot.com',
  );

  // ==================== LINUX ====================
  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'YOUR_LINUX_API_KEY',
    appId: 'YOUR_LINUX_APP_ID',
    messagingSenderId: '994450931333',
    projectId: 'ecommerce-39840',
    storageBucket: 'ecommerce-39840.appspot.com',
  );
}
